### PR TITLE
Don't allow app name translation

### PR DESCRIPTION
**Pull request by licaon-kter**

### CODE REVIEW

**Comment by licaon-kter** [comment]
Wheren't auto-removed by Weblate at sync time?

**Comment by bilde2910** [comment]
I don't think weblate removes them. I'm not sure. Removing them manually just for good measure. Thanks for the contribution though, merging :+1:

**Comment by licaon-kter** [comment]
Oh, also the ones in the PHP files...not sure how to tackle them...make them hardcoded?

**Comment by bilde2910** [comment]
Forgot about that one. There's one instance in the frontend. Removing it now.

**Pull request merged**
