### PR TITLE
Add donation link to README

### PR DESCRIPTION
**Pull request by natrius**
Add donation link!

### CODE REVIEW

**Comment by bilde2910** [comment]
I didn't really consider adding this, but I guess it doesn't do any harm. Mind if I change the phrasing a little bit before I merge?

**Comment by natrius** [comment]
No worries, change how you would like, it was just a suggestion to add it, because i got asked already twice on how to donate to you. I found the link :)

Keep in mind, if you publish on google, google might be picky about donations.

**Comment by bilde2910** [comment]
I see. Thanks for the shout out then :)

Posting this on Google Play is not currently on the roadmap, unless I get demand for it/reason to do so.

**Comment by natrius** [comment]
AS far as  I know you can safe your app-name even if you don't plan to publish, so nobody else can distribute a malicious app in your name. You might look into that. Read about that somewhere somewhen.

**Comment by bilde2910** [comment]
That sounds like a plan if I can figure it out. Will have to look into it.

**Comment by bilde2910** [comment]
The app is now live on Google Play: https://play.google.com/store/apps/details?id=info.varden.hauk

**Pull request merged**
