### PR TITLE
Consistency - shares not users

### PR DESCRIPTION
**Pull request by licaon-kter**

### CODE REVIEW

**Comment by bilde2910** [comment]
A share can have one or more members. Shares with more than one member are called group shares, see e.g. the selector for "sharing mode" on the app. They're still just one share, however. So when you view a group share in the browser, you're viewing one share with multiple members/participants.

**Comment by licaon-kter** [comment]
I can add a group share to a group share?

I thought an entry is one individual share

**Comment by bilde2910** [comment]
You can't add two group shares together, but you can add a single user share to a group share. What actually happens when you do that, is that the owner of the single user share starts broadcasting to two shares instead of just one - his own personal share, and the group share in question. The group share will also show up as a separate share in the app for that person, as "Group share (member)". Hence, they will then have an active participation in multiple shares.

When you use the "Create new tracking link" button, that also creates a new share, but is still the same user.

**Comment by licaon-kter** [comment]
I think we are lost in translation here, I know what's going on.

Not sure why those need to be "users" in this one string when they're called "shares" elsewhere?

**Comment by bilde2910** [comment]
I think that may be a case to rephrase the others away from "share" in that case. I may not have chosen the best phrasing for some of the strings. I'll push some commits here

**Comment by bilde2910** [comment]
Pushed a commit above. If I missed any, feel free to let me know

**Pull request closed without merging**
